### ISSUE TITLE
How to obtain coefficients of FTT?

### ISSUE THREAD

**Issue by honglizhaobob** [goroda/Compressed-Continuous-Computation#12]
Hi, 

I have been using the C3 toolbox Python interface for a regression task. I was wondering if it is possible to dump out the coefficient tensor train (assuming Legendre basis) from `c3py`, or if I'd need to dig into the C code to do so.

Thanks very much for any suggesions.

**Comment by goroda** [comment]
Currently, this is not exposed in the python interface. However, the general structure is that the parameters of the function train are stored with each univariate function, not as a coefficient tensor. Each individual function is accessible through the get_uni_function func. There are examples in https://github.com/goroda/Compressed-Continuous-Computation/blob/master/pyexamples/c3py_look_at_unis.py

I will try to implement a way to also access the parameters of each univariate function from python soon.

**Comment by honglizhaobob** [comment]
Thanks a lot, this is very helpful!
