### ISSUE TITLE
Feature Request: Pytorch Support for GPU Utilization in c3py and potential issues.

### ISSUE THREAD

**Issue by xueminchi** [goroda/Compressed-Continuous-Computation#13]
@goroda 
**Is your feature request related to a problem? Please describe.**
Hi, dear professor Alex Gorodetsky. Thanks for releasing and maintaining the tool. I've read your papers on the continuous tensor train approximation and am currently playing with these Python examples by importing `c3py` package, the Python interface. So far I haven't encountered an issue, I just wonder if it is possible to make it support Pytorch instead of Numpy by modifying the `c3py` using Pytorch instead of Numpy? The reason is that I want to use the FT on a GPU as a part of an algorithm when the problem is very large scale. Will this modification cause any potential issues?

**Describe the solution you'd like**
The FT data type is built on top of the Pytorch tensor and can be put on the device `CPU` or `GPU`.

@xueminchi

**Comment by goroda** [comment]
This is a good suggestion. The main reason this cannot be currently done is that underneath the hood the manipulations and code are all in C. Numpy is not used for the actual algorithms, but rather as an interface for the arrays. From this perspective, one can build an interface to pytorch, but this still wouldn't allow performance to be accelerated.  This may be addressed in the future, but there are no current plans.
