### ISSUE TITLE
error during install

### ISSUE THREAD

**Issue by FloraHF** [goroda/Compressed-Continuous-Computation#6]
Hi, I'm trying to install c3 on my computer, after I type in cmake .., it gives me this error:

-- Looking for cheev_
-- Looking for cheev_ - not found
-- Looking for cheev_
-- Looking for cheev_ - not found
CMake Error at /usr/share/cmake-3.2/Modules/FindLAPACK.cmake:342 (message):
  A required library with LAPACK API not found.  Please specify library
  location.
Call Stack (most recent call first):
  CMakeLists.txt:41 (find_package)

I've already installed BLAS and LAPACK, and I'm using ubuntu 14 with GCC 5. 
could you kindly give some clue what the reason might be?

**Comment by goroda** [comment]
Which lapack library are you using and how did you install it? Are you sure it is located in your search path?

On ubuntu it could be a good idea to have the following packages installed
liblapack-doc
liblapack-dev

**Comment by goroda** [comment]
you may be able to provide the library locations for lapack using the following options
set(BLAS_DIR /path/to/blas)
find_package(BLAS REQUIRED)
set(LAPACK_DIR /path/to/lapack)
find_package(LAPACK REQUIRED)

in other words running with 
>> cmake -DLAPACK_DIR:FILEPATH=<path/to/lapack> ..

If it is working for you I will close the issue.

**Comment by FloraHF** [comment]
I reinstalled my ubuntu, it works now! Thank you very much!
