### ISSUE TITLE
Issues with having a file named pytest.py in the path

### ISSUE THREAD

**Issue by calewis** [goroda/Compressed-Continuous-Computation#7]
I have installed the python wrappers by following the directions of the README, but I get an issue whereby the pytest.py file is getting (unintentionally?) picked up by libraries that I import. 

I have the following env: 
```
C3HOME=~/software/C3/Compressed-Continuous-Computation
PYTHONPATH=~/software/C3/Compressed-Continuous-Computation/wrappers/python
```

The following script will cause `$C3HOME/wrappers/python/pytest.py` to run
```python
from sklearn import linear_model
```

if I invoke with `python -v my_script` we see that sklearn is somehow calling the pytest file
```
import sklearn.utils._unittest_backport # precompiled from ~/Library/Python/2.7/lib/python/site-packages/sklearn/utils/_unittest_backport.pyc
# ~/software/C3/Compressed-Continuous-Computation/wrappers/python/pytest.pyc matchess ~/software/C3/Compressed-Continuous-Computation/wrappers/python/pytest.py
```

If I rename the pytest.py file to something else this issue goes away.

**Comment by goroda** [comment]
I moved all the python examples to a new highlevel directory called pyexamples
